[build]
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/.well-known/*"
to = "/.well-known/:splat"
status = 200

[[redirects]]
from = "/"
to = "https://talks.ayaka.io/nekoayaka/2023-12-21-deep-dive-llm-unleash-the-potentials-of-llm-share/"
status = 301

[[redirects]]
from = "/nekoayaka/2023-12-21-deep-dive-llm-unleash-the-potentials-of-llm-share/*"
to = "/nekoayaka/2023-12-21-deep-dive-llm-unleash-the-potentials-of-llm-share/index.html"
status = 200
